application:
  actions: actions
  web: web-src
  runtimeManifest:
    packages:
      orderService:
        license: Apache-2.0
        actions:
          orderService:
            function: actions/orderService/index.js
            web: 'yes'
            runtime: 'nodejs:14'
            inputs:
              LOG_LEVEL: debug
            annotations:
              require-adobe-auth: true
              final: true
          order-publish:
            function: actions/order-publish/index.js
            web: 'yes'
            runtime: 'nodejs:14'
            inputs:
              LOG_LEVEL: debug
              apiKey: $SERVICE_API_KEY
            annotations:
              require-adobe-auth: true
              final: true
